# Generated by Django 6.0 on 2025-12-25 18:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(help_text='Capacité en kg')),
                ('power', models.IntegerField(help_text='Puissance en CV')),
                ('motorization', models.CharField(choices=[('Diesel', 'Diesel'), ('Essence', 'Essence'), ('Électrique', 'Électrique'), ('Hybride', 'Hybride')], max_length=20)),
                ('tank_capacity', models.IntegerField(help_text='Capacité du réservoir en litres')),
                ('current_fuel', models.FloatField(default=0, help_text='Carburant actuel en litres')),
                ('fuel_percentage', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trucks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('contractual_hours', models.IntegerField(default=40)),
                ('hours_worked', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drivers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=100)),
                ('departure_address', models.TextField()),
                ('pickup_time', models.DateTimeField()),
                ('arrival_city', models.CharField(max_length=100)),
                ('arrival_address', models.TextField()),
                ('expected_dropoff_time', models.DateTimeField()),
                ('container_number', models.CharField(max_length=50)),
                ('container_type', models.CharField(choices=[('20ft', '20 pieds'), ('40ft', '40 pieds'), ('40ft HC', '40 pieds HC')], max_length=20)),
                ('distance', models.IntegerField(help_text='Distance en km')),
                ('estimated_fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_fuel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('hours_worked', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='api.driver')),
                ('truck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='api.truck')),
            ],
            options={
                'db_table': 'missions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('mission', 'Mission'), ('fuel', 'Carburant'), ('maintenance', 'Maintenance'), ('general', 'Général')], default='general', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.driver')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Quantité en litres')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entries', to='api.mission')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='api.truck')),
            ],
            options={
                'db_table': 'fuel_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_kilometers', models.IntegerField(default=0)),
                ('total_hours_worked', models.FloatField(default=0)),
                ('completed_missions', models.IntegerField(default=0)),
                ('average_speed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_stats', to='api.driver')),
            ],
            options={
                'db_table': 'weekly_stats',
                'ordering': ['-week_start'],
                'unique_together': {('driver', 'week_start')},
            },
        ),
    ]
