# Generated by Django 6.0 on 2026-01-03 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelentry',
            options={},
        ),
        migrations.RemoveField(
            model_name='fuelentry',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='fuelentry',
            name='notes',
        ),
        migrations.AlterField(
            model_name='fuelentry',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuelentry',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fuelentry',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.truck'),
        ),
        migrations.AlterModelTable(
            name='fuelentry',
            table=None,
        ),
    ]
