# Generated by Django 6.0 on 2026-01-03 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_fuelentry_options_remove_fuelentry_mission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entries', to='api.mission'),
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='arrival_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='arrival_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='arrival_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='departure_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='departure_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='departure_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fuelentry',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fuelentry',
            name='quantity',
            field=models.FloatField(help_text='Quantité en litres'),
        ),
        migrations.AlterField(
            model_name='fuelentry',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='api.truck'),
        ),
        migrations.AlterModelTable(
            name='fuelentry',
            table='fuel_entries',
        ),
    ]
