# Generated by Django 6.0 on 2026-01-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_fuelentry_options_fuelentry_mission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='avg_consumption',
            field=models.FloatField(default=25.0, help_text='Consommation moyenne en litres/100km'),
        ),
    ]
